// Content model for every specimen in the explorer.
// Positions on hotspots are in the LOCAL coordinate space of each organ's
// generated geometry (see organGeometry.js) — roughly a -1.5..1.5 cube.

export const ORGANS = [
  {
    id: "heart",
    name: "Heart",
    system: "Circulatory System",
    icon: "♥",
    tagline: "The tireless pump",
    color: "#d8776e",
    accent: "#ff8a7a",
    description:
      "A four-chambered muscular pump that drives blood through the body via rhythmic, involuntary contraction, delivering oxygen and nutrients to every tissue.",
    facts: [
      { key: "Size", val: "About the size of a fist" },
      { key: "Weight", val: "250–350 g" },
      { key: "Beats / day", val: "~100,000" },
      { key: "Output", val: "~5 L blood / min" },
      { key: "Chambers", val: "4 (2 atria, 2 ventricles)" },
    ],
    medical: "A heart attack occurs when a coronary artery is blocked, starving heart muscle of oxygen.",
    fun: "Over an average lifetime, the heart beats more than 2.5 billion times without pausing to rest.",
    hotspots: [
      { id: "aorta", label: "Aorta", position: [0.15, 1.35, 0.1], desc: "The body's largest artery, carrying oxygen-rich blood from the left ventricle out to the entire body." },
      { id: "leftAtrium", label: "Left Atrium", position: [-0.75, 0.65, 0.55], desc: "Receives oxygenated blood returning from the lungs via the pulmonary veins." },
      { id: "rightVentricle", label: "Right Ventricle", position: [0.55, -0.35, 0.85], desc: "Pumps deoxygenated blood into the pulmonary artery, sending it to the lungs to pick up oxygen." },
      { id: "apex", label: "Apex", position: [-0.1, -1.3, 0.25], desc: "The pointed lower tip of the heart, formed mostly by the left ventricle — where a stethoscope best hears the heartbeat." },
    ],
  },
  {
    id: "brain",
    name: "Brain",
    system: "Nervous System",
    icon: "◉",
    tagline: "Three pounds of electricity",
    color: "#c98fae",
    accent: "#e2a8c8",
    description:
      "The command center of the nervous system, coordinating thought, memory, emotion, movement, and every sense — via roughly 86 billion interconnected neurons.",
    facts: [
      { key: "Weight", val: "~1.4 kg" },
      { key: "Neurons", val: "~86 billion" },
      { key: "Power draw", val: "~20 W (20% of body's energy)" },
      { key: "Water content", val: "~73%" },
      { key: "Signal speed", val: "Up to 120 m/s" },
    ],
    medical: "Strokes occur when blood supply to part of the brain is interrupted, and rapid treatment preserves function.",
    fun: "The brain has no pain receptors of its own — brain surgery can be performed on a fully awake patient.",
    hotspots: [
      { id: "cortex", label: "Cerebral Cortex", position: [0, 0.85, 0.9], desc: "The wrinkled outer layer responsible for higher functions: reasoning, language, and voluntary movement." },
      { id: "cerebellum", label: "Cerebellum", position: [0, -0.55, -1.05], desc: "Tucked beneath the cortex, it fine-tunes balance, posture, and coordinated movement." },
      { id: "brainstem", label: "Brainstem", position: [0.05, -1.25, -0.15], desc: "Controls essential involuntary functions — breathing, heart rate, and consciousness itself." },
      { id: "hemisphere", label: "Longitudinal Fissure", position: [0.02, 0.9, 0.1], desc: "The deep groove dividing the brain into left and right hemispheres." },
    ],
  },
  {
    id: "lungs",
    name: "Lungs",
    system: "Respiratory System",
    icon: "❋",
    tagline: "The living bellows",
    color: "#e39a9a",
    accent: "#f0b4b4",
    description:
      "A pair of spongy, air-filled organs that exchange oxygen and carbon dioxide with the blood across roughly 300 million tiny air sacs called alveoli.",
    facts: [
      { key: "Surface area", val: "~70 m² (a tennis court)" },
      { key: "Breaths / day", val: "~20,000" },
      { key: "Alveoli", val: "~480 million" },
      { key: "Air moved / day", val: "~11,000 L" },
      { key: "Lobes", val: "3 right, 2 left" },
    ],
    medical: "The right lung has three lobes while the left has only two, leaving room for the heart.",
    fun: "Laid out flat, the internal surface of both lungs would cover an area about the size of a tennis court.",
    hotspots: [
      { id: "trachea", label: "Trachea", position: [0, 1.4, 0.1], desc: "The windpipe, reinforced with cartilage rings, carrying air down toward the bronchi." },
      { id: "leftLung", label: "Left Lung", position: [-0.95, 0.1, 0.4], desc: "Smaller than the right lung, with a notch shaped to accommodate the heart." },
      { id: "rightLung", label: "Right Lung", position: [0.95, 0.1, 0.4], desc: "Larger and divided into three lobes, doing slightly more of the body's gas exchange." },
      { id: "bronchi", label: "Bronchi", position: [0, 0.95, 0.3], desc: "The two branching tubes that carry air from the trachea into each lung." },
    ],
  },
  {
    id: "liver",
    name: "Liver",
    system: "Digestive System",
    icon: "◈",
    tagline: "The chemical factory",
    color: "#a8524a",
    accent: "#c56f5f",
    description:
      "The body's largest internal organ, filtering blood from the digestive tract, metabolizing nutrients, and producing bile to help digest fats.",
    facts: [
      { key: "Weight", val: "~1.5 kg" },
      { key: "Functions", val: "500+ known" },
      { key: "Blood filtered", val: "~1.4 L / min" },
      { key: "Regeneration", val: "Can regrow from 25%" },
      { key: "Lobes", val: "2 (right larger, left smaller)" },
    ],
    medical: "The liver is one of the only internal organs capable of regenerating lost tissue back to near-full size.",
    fun: "A healthy liver can regenerate to its original size even after up to 70% of it is surgically removed.",
    hotspots: [
      { id: "rightLobe", label: "Right Lobe", position: [0.65, 0.15, 0.5], desc: "The larger of the liver's two main lobes, occupying most of the upper-right abdomen." },
      { id: "leftLobe", label: "Left Lobe", position: [-0.75, -0.1, 0.35], desc: "The smaller lobe, extending across toward the stomach." },
      { id: "portalVein", label: "Portal Vein", position: [-0.05, -0.25, 0.95], desc: "Carries nutrient-rich blood from the intestines into the liver for processing." },
      { id: "gallbladderBed", label: "Gallbladder Bed", position: [0.55, -0.55, 0.75], desc: "The underside groove where the gallbladder nestles, storing bile the liver produces." },
    ],
  },
  {
    id: "kidneys",
    name: "Kidneys",
    system: "Urinary System",
    icon: "◑",
    tagline: "The body's filter",
    color: "#8a4a4a",
    accent: "#b06a63",
    description:
      "A pair of bean-shaped organs that filter waste and excess fluid from the blood, regulate electrolytes, and produce urine.",
    facts: [
      { key: "Size", val: "~11 cm long" },
      { key: "Blood filtered", val: "~180 L / day" },
      { key: "Nephrons", val: "~1 million each" },
      { key: "Urine produced", val: "~1.5 L / day" },
      { key: "Weight", val: "~150 g each" },
    ],
    medical: "People can live a full, healthy life with just one functioning kidney, which is why living donation is possible.",
    fun: "Each kidney contains about a million microscopic filters called nephrons, laid end to end they'd stretch for miles.",
    hotspots: [
      { id: "cortex", label: "Renal Cortex", position: [0.0, 0.5, 0.55], desc: "The outer layer, packed with filtering units called nephrons." },
      { id: "hilum", label: "Renal Hilum", position: [0.55, 0.0, 0.1], desc: "The indented notch where the renal artery, vein, and ureter connect to the kidney." },
      { id: "ureter", label: "Ureter", position: [0.35, -1.15, 0.0], desc: "The muscular tube that carries urine down to the bladder in rhythmic waves." },
      { id: "artery", label: "Renal Artery", position: [0.75, 0.15, 0.25], desc: "Delivers roughly a quarter of the heart's total output to the kidney for filtering." },
    ],
  },
  {
    id: "eye",
    name: "Eye",
    system: "Sensory System",
    icon: "◎",
    tagline: "A window made of light",
    color: "#5d8fc9",
    accent: "#7dabe6",
    description:
      "A precision optical organ that focuses light onto a layer of photoreceptor cells, converting it into neural signals the brain interprets as vision.",
    facts: [
      { key: "Size", val: "~24 mm across" },
      { key: "Weight", val: "~7.5 g" },
      { key: "Movements", val: "Thousands / day" },
      { key: "Blood supply", val: "Ophthalmic artery" },
      { key: "Focusing power", val: "~60 diopters" },
    ],
    medical: "The retina is technically an extension of the central nervous system, not a separate sensory organ.",
    fun: "The cornea carries no blood vessels at all — it draws the oxygen it needs directly from the air.",
    hotspots: [
      { id: "pupil", label: "Pupil", position: [0.15, 0.05, 1.15], desc: "The dark opening that widens or narrows to control how much light enters the eye." },
      { id: "iris", label: "Iris", position: [-0.3, 0.35, 1.1], desc: "The coloured muscular ring that adjusts pupil size in response to light." },
      { id: "opticNerve", label: "Optic Nerve", position: [0.55, -0.05, -1.35], desc: "A bundle of roughly a million nerve fibers relaying visual signals to the brain." },
      { id: "sclera", label: "Sclera", position: [0.85, 0.75, 0.35], desc: "The tough white outer coat that gives the eyeball its shape and protects inner structures." },
    ],
  },
  {
    id: "intestine",
    name: "Intestine",
    system: "Digestive System",
    icon: "≋",
    tagline: "Seven meters, coiled tight",
    color: "#d99a8e",
    accent: "#e8b4a6",
    description:
      "A long, coiled tube where digestion finishes and nutrients are absorbed into the bloodstream, hosting trillions of microbes along the way.",
    facts: [
      { key: "Length", val: "~7 m (small + large)" },
      { key: "Absorption area", val: "~30 m²" },
      { key: "Transit time", val: "24–72 hours" },
      { key: "Microbes", val: "Trillions of bacteria" },
      { key: "Sections", val: "Duodenum, jejunum, ileum, colon" },
    ],
    medical: "The gut houses roughly 70% of the body's immune cells, guarding against pathogens entering with food.",
    fun: "The small intestine's inner lining is so folded and finger-like that, unrolled, it could cover a tennis court.",
    hotspots: [
      { id: "duodenum", label: "Duodenum", position: [0.4, 1.1, 0.3], desc: "The short first stretch, where digestive juices from the liver and pancreas mix with food." },
      { id: "jejunum", label: "Jejunum & Ileum", position: [-0.5, 0.1, 0.5], desc: "The long coiled middle and final sections, doing most of the work of nutrient absorption." },
      { id: "colon", label: "Large Intestine", position: [0.7, -0.9, -0.3], desc: "Absorbs water and salts from remaining waste, compacting it before elimination." },
    ],
  },
  {
    id: "pancreas",
    name: "Pancreas",
    system: "Endocrine System",
    icon: "▲",
    tagline: "Sugar's quiet regulator",
    color: "#d1a85c",
    accent: "#e6c17e",
    description:
      "A slender gland behind the stomach that produces digestive enzymes and hormones — chiefly insulin and glucagon — to regulate blood sugar.",
    facts: [
      { key: "Length", val: "~15 cm" },
      { key: "Weight", val: "~80 g" },
      { key: "Enzymes made", val: "~1.5 L digestive juice / day" },
      { key: "Key hormones", val: "Insulin, glucagon" },
      { key: "Islet cells", val: "~1 million clusters" },
    ],
    medical: "Type 1 diabetes occurs when the immune system destroys the insulin-producing cells of the pancreas.",
    fun: "The insulin-producing 'islets of Langerhans' make up barely 1–2% of the pancreas's total mass.",
    hotspots: [
      { id: "head", label: "Head", position: [0.85, 0.15, 0.2], desc: "The wide right end, nestled snugly in the curve of the duodenum." },
      { id: "body", label: "Body", position: [0.0, -0.05, 0.15], desc: "The central section, home to the majority of the hormone-producing islet cells." },
      { id: "tail", label: "Tail", position: [-0.95, -0.05, 0.05], desc: "The narrow left tip, reaching toward the spleen." },
    ],
  },
  {
    id: "skin",
    name: "Skin",
    system: "Integumentary System",
    icon: "▤",
    tagline: "The largest organ, worn outside",
    color: "#d9b98c",
    accent: "#e8cba3",
    description:
      "A three-layer barrier organ that regulates temperature, senses the world through touch, and defends the body from injury, infection, and UV light.",
    facts: [
      { key: "Surface area", val: "~1.8–2.0 m²" },
      { key: "Weight", val: "~4 kg (heaviest organ)" },
      { key: "Renewal", val: "New outer layer every ~28 days" },
      { key: "Layers", val: "Epidermis, dermis, hypodermis" },
      { key: "Receptors", val: "Millions of nerve endings" },
    ],
    medical: "Sunburn is UV damage to skin cell DNA — repeated damage raises long-term skin cancer risk.",
    fun: "You shed roughly 500 million skin cells every single day — most household dust is partly made of them.",
    hotspots: [
      { id: "epidermis", label: "Epidermis", position: [0.0, 1.1, 0.55], desc: "The thin, tough outer layer, constantly renewing and providing waterproof protection." },
      { id: "dermis", label: "Dermis", position: [0.0, 0.15, 0.55], desc: "A thicker layer packed with blood vessels, nerve endings, hair follicles, and glands." },
      { id: "hypodermis", label: "Hypodermis", position: [0.0, -0.95, 0.55], desc: "The fatty innermost layer, cushioning the body and storing energy." },
      { id: "follicle", label: "Hair Follicle", position: [0.55, 0.55, 0.75], desc: "A tunnel-shaped structure anchoring each hair, rooted deep in the dermis." },
    ],
  },
];

export function getOrgan(id) {
  return ORGANS.find((o) => o.id === id) || ORGANS[0];
}
